#!/usr/bin/env bash
TOOLS_WS=${TOOLS_WS:-$(pwd)}
multi_node=0

function check_ceph_status() {
    if [ $SKIP_CEPH_STATUS -ne 0 ]
    then
        return 0
    fi
    
    echo "Connect to config node to check ceph -s output"
    /usr/local/bin/sshpass -p $SM_SERVER_PASSWORD ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -l $SM_SERVER_LOGIN $SM_SERVER_IP " (
    set -e 
    $SM_FILES_DIR/check_ceph_status.py $CLUSTER_NAME $EXPECTED_OSD_COUNT

    ) "
    if [ $? == 0 ]
    then
        echo "ceph status verification is sucessfull!!!"
    else
        echo "ERROR: ceph status verification failed!!! aborting the process"
        exit 1
    fi

}

# This function will reimage the provided setup.
# Performs the following steps:
# Adds the iso and contrail packages to SM database
# Adds cluster and servers to SM database
# Does reimage of the setup.
function reimage_using_SM_ceph() {
    if [ $SKIP_REIMAGE -ne 0 ]
    then
        return 0
    fi
    # set the parameters required for reimage.
    if [[ $DISTRO =~ ubuntu-12.04 ]]; then
        image="/root/images/ubuntu-12.04.3-server-amd64.iso" 
        pkg_type="contrail-ubuntu-package"
        storage_pkg_type="contrail-storage-ubuntu-package"
        iso_type="ubuntu"
        SMID=ubuntu12$SKU${BUILDID}
    elif [[ $DISTRO =~ ubuntu-14.04 ]]; then 
        image="/root/images/ubuntu-14.04.1-server-amd64.iso"
        pkg_type="contrail-ubuntu-package"
        storage_pkg_type="contrail-storage-ubuntu-package"
        iso_type="ubuntu"
        SMID=ubuntu14$SKU${BUILDID}
    elif [[ $DISTRO =~ centos64 ]]; then 
        image="/root/images/CentOS-6.4-x86_64-minimal.iso"
        pkg_type="contrail-centos-package"
        iso_type="centos"
        SMID=centos64$SKU${BUILDID}
    elif [[ $DISTRO =~ centos65 ]]; then 
        image="/root/images/CentOS-6.5-x86_64-minimal.iso"
        pkg_type="contrail-centos-package"
        iso_type="centos"
        SMID=centos65$SKU${BUILDID}
    fi

    SMID=`echo $SMID | tr '[:upper:]' '[:lower:]'`

    #set the parameters for multi/single node setup
    cluster_json="$SM_FILES_DIR/$CLUSTER_FILE_NAME.json"
    server_json="$SM_FILES_DIR/$SERVER_FILE_NAME.json"

    echo "Connect to SM_SERVER to reimage and provision the targets"
    /usr/local/bin/sshpass -p $SM_SERVER_PASSWORD ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -l root $SM_SERVER_IP " (
        set -e
        echo "add required image/server/cluster for reimage and provision of the target"

        echo "delete iso image if it exists"
        if [ ${BRANCH} == "R1.10" ]
        then
            server-manager delete image ${DISTRO}
        else
            server-manager delete image --image_id ${DISTRO}
        fi

        echo "add base ISO image to server manager database"
        if [ ${DISTRO} == "ubuntu-14-04" ]
        then
            server-manager add image -f /root/images/image14.json
        else
            #server-manager upload_image $DISTRO ${REIMAGE_PARAM} $iso_type $image
            server-manager add image -f /root/images/image12.json
        fi
        if [ $? == 0 ]
        then
            echo "Server-manager adding image command is successful"
        else
            echo "Server-manager adding image command failed, aborting the process"
            exit 1
        fi

        echo "check if the image was added successfully"
        server-manager show image | grep $DISTRO
        if [ $? != 0 ] 
        then
            echo "Adding Base ISO image failed"
            exit 1
        fi

        echo "delete contrail package if it exists"
        if [ ${BRANCH} == "R1.10" ]
        then
            server-manager delete image $SMID
        else
            server-manager delete image --image_id $SMID
        fi
        echo "add contrail package to the SM database"
      
        echo "server-manager upload_image $SMID ${BUILDID} $pkg_type $PKG_FILE"
        server-manager upload_image $SMID ${BUILDID} $pkg_type $PKG_FILE
        if [ $? == 0 ]
        then
            echo "Server-manager adding contrail-package command is successful"
        else
            echo "Server-manager adding contrail-package command failed, aborting the process"
            exit 1
        fi

        echo "delete contrail storage package if it exists"
        if [ ${BRANCH} == "R1.10" ]
        then
            server-manager delete image contrail-storage-packages
        else
            server-manager delete image --image_id contrail-storage-packages
        fi

        echo "add contrail storage package to the SM database"
      
        server-manager upload_image contrail-storage-packages ${BUILDID} ${storage_pkg_type} $STORAGE_PKG_FILE
        if [ $? == 0 ]
        then
            echo "Server-manager adding storage-package command is successful"
        else
            echo "Server-manager adding storage-package command failed, aborting the process"
            exit 1
        fi

        echo "check if the package was added successfully"
        server-manager show image | grep contrail-storage-packages
        if [ $? != 0 ] 
        then
            echo "Adding storage-packages contrail-storage-packages failed"
            exit 1
        fi

        server-manager show image

        echo "add cluster to SM database"
        server-manager add cluster -f $cluster_json
        if [ $? == 0 ]
        then
            echo "Adding cluster to server-manager is sucessful!!!"
        else
            echo "Adding cluster to server-manager failed, aborting the process"
            exit 1
        fi

        server-manager show cluster --detail

        echo "add server to SM database"
        echo "server-manager add server -f $server_json"
        server-manager add server -f $server_json
        if [ $? == 0 ]
        then
            echo "Adding server to server-manager is sucessful!!!"
        else
            echo "Adding server to server-manager failed, aborting the process"
            exit 1
        fi

        server-manager show server --detail

        echo "reimage the target setup"
        echo "server-manager reimage -F --cluster_id $CLUSTER_NAME $DISTRO"
        server-manager reimage -F --cluster_id $CLUSTER_NAME $DISTRO

        if [ $? == 0 ]
        then
            echo "Issue of Reimage command to reimage target nodes is sucessful!!!"
        else
            echo "Issue of Reimage command to reimage target nodes failed, aborting the process"
            exit 1
        fi

        #echo "reimage in progress please wait ..."
        #sleep 10
 
        #check if reimage is completed.
        #echo "/root/sm_files/check_reimage.sh $CLUSTER_NAME"
        #/root/sm_files/check_reimage.sh $CLUSTER_NAME
        $SM_FILES_DIR/check_reimage_complete.py
        if [ $? == 0 ]
        then
            echo "check_reimage_complete.py : reimaged the target $CLUSTER_NAME successfully"
        else
            echo "check_reimage_complete.py: reimage of target $CLUSTER_NAME failed!!!"
            exit 1
        fi

    ) "
    if [ $? == 0 ]
    then
        echo "reimaged the target $CLUSTER_NAME successfully"
        sleep 150
    else
        echo "reimage of target $CLUSTER_NAME failed!!!"
        exit 1
    fi
}

function run_smgr_task_ceph() {
    echo "Running tests on $1.."

    if [ ${TEST_SETUP} == "SINGLENODE" ]
    then
        multi_node=0
    elif [ ${TEST_SETUP} == "MULTINODE" ]
    then
        multi_node=1
    else
        echo "TEST_SETUP is not defined, abort the process"
        exit 1
    fi

    if [ -z "$SM_SERVER_IP" ]
    then
        echo "SM_SERVER_IP is not set, unable to proceede, aborting the process"
        exit 1
    fi

    if [ -z $CLUSTER_NAME ] && [ -z $SERVER_NAME ]; then
        echo "CLUSTER_NAME/SERVER_NAME env is not set, aborting the process"
        exit 1
    fi
    create_testbed_ceph || die "Failed to create required testbed details"
    bringup_SM_setup || die "Failed to bringup SM setup" 
    reimage_using_SM_ceph || die "reimage failed"
    provision_using_SM || die "provision failed"
    #install_ant || die "ant installation failed on cfgm"
    check_ceph_status || die "Run_sanity step failed"
    #run_tempest || die "Run_Tempest step failed"
    #collect_tech_support || die "Task to collect logs/cores failed"
    echo "Ending test on $1"
}
