#!/usr/bin/env bash
TOOLS_WS=${TOOLS_WS:-$(pwd)}
source $TOOLS_WS/testers/environment.sh
source $TOOLS_WS/testers/smgr_utils_ceph

function get_ubuntu_image_id () {
  if [ $1 = ubuntu-12-04 ]; then
   eval "$2=ubuntu-12.04.3"
  elif [ $1 = ubuntu-14-04 ];then
   eval "$2=ubuntu-14.04"
  fi
}

##
# search_package
function search_package_ceph {

    if [ $PKG_LOCAL -eq 1 ] && [ $INSTALL_MODE == "SM" ]
    then
      SM_INSTALLER_PKG_FILE=`exec_cmds -s ${TASK_RUNNER_HOST_STRING} -p ${TASK_RUNNER_HOST_PASSWORD} -c "
            ls $PKG_LOCAL_PATH/$SM_SERVER_PKG_FILE_LOCAL
            "` || die "Unable to find SM LOCAL PACKAGE.Copy it to SM/TASK_RUNNER node"
      SM_INSTALLER_PKG_FILE=$(echo "${SM_INSTALLER_PKG_FILE}" | sed -e 's/\r//g;s/ //g;s/^$//g')
    elif [ $INSTALL_MODE == "SM" ] && [ $SM_TYPE == "ubuntu" ]
    then
      SM_INSTALLER_PKG_FILE=`ls ${BUILD_PREFIX}/${BRANCH}/${BUILDID}/${DISTRO}/${SKU}/artifacts/contrail-server-manager-installer_*\.*-${BUILDID}\~$SKU\_all.deb*` || die "Unable to find SM install package"
    elif [ $INSTALL_MODE == "SM" ] && [ $SM_TYPE == "centos" ]
    then
      SM_INSTALLER_PKG_FILE=`ls ${BUILD_PREFIX}/${BRANCH}/${BUILDID}/${DISTRO}/${SKU}/artifacts/contrail-server-manager-installer-*\.*-${BUILDID}\~$SKU.el6.noarch.rpm*` || die "Unable to find SM install package"
    fi

    if [ $PKG_LOCAL -eq 1 ]
    then
      INSTALL_PKG_FILE=`exec_cmds -s ${TASK_RUNNER_HOST_STRING} -p ${TASK_RUNNER_HOST_PASSWORD} -c "
                     ls $PKG_LOCAL_PATH/$INSTALL_PKG_FILE_LOCAL
                     "` || die "Unable to find Contrail-install LOCAL PACKAGE.Copy it to SM/TASK_RUNNER node"
      INSTALL_PKG_FILE=$(echo "${INSTALL_PKG_FILE}" | sed -e 's/\r//g;s/ //g;s/^$//g')
      STORAGE_PKG_FILE=`exec_cmds -s ${TASK_RUNNER_HOST_STRING} -p ${TASK_RUNNER_HOST_PASSWORD} -c "
                     ls $PKG_LOCAL_PATH/$STORAGE_PKG_FILE_LOCAL
                     "` || die "Unable to find storage LOCAL PACKAGE.Copy it to SM/TASK_RUNNER node" 
      STORAGE_PKG_FILE=$(echo "${STORAGE_PKG_FILE}" | sed -e 's/\r//g;s/ //g;s/^$//g')
    else
      INSTALL_PKG_FILE=`ls ${BUILD_PREFIX}/${BRANCH}/${BUILDID}/${DISTRO}/${SKU}/contrail-install-packages*` || die "Unable to find install package"
      STORAGE_PKG_FILE=`ls ${BUILD_PREFIX}/${BRANCH}/${BUILDID}/${DISTRO}/${SKU}/artifacts/contrail-storage-packages*~${SKU}_all.deb` || die "Unable to find storage package"
    fi

    export INSTALL_PKG_TYPE="contrail-ubuntu-package"
    export STORAGE_PKG_TYPE="contrail-storage-ubuntu-package"
    export INSTALL_PKG_FILE=$INSTALL_PKG_FILE
    export STORAGE_PKG_FILE=$STORAGE_PKG_FILE
    export SM_INSTALLER_PKG_FILE=$SM_INSTALLER_PKG_FILE

    REIMAGE_PARAM="REIMAGE_PARAM"
    get_ubuntu_image_id ${DISTRO} $REIMAGE_PARAM
    export REIMAGE_PARAM
    export PKG_FILE_DIR=`dirname $INSTALL_PKG_FILE`

}

function update_testbed_file {

    iface=`sshpass -p ${TASK_RUNNER_HOST_PASSWORD} ssh -t -t -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${TASK_RUNNER_HOST_STRING} '(
       /home/stack/get_pvt_iface.py HOST1
      )'`
    sed -i "s/HOST1_IFACE/$iface/" $ABS_PATH_TBFILE

    iface=`sshpass -p ${TASK_RUNNER_HOST_PASSWORD} ssh -t -t -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${TASK_RUNNER_HOST_STRING} '(
       /home/stack/get_pvt_iface.py HOST2
      )'`
    sed -i "s/HOST2_IFACE/$iface/" $ABS_PATH_TBFILE

    iface=`sshpass -p ${TASK_RUNNER_HOST_PASSWORD} ssh -t -t -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${TASK_RUNNER_HOST_STRING} '(
       /home/stack/get_pvt_iface.py HOST3
      )'`
    sed -i "s/HOST3_IFACE/$iface/" $ABS_PATH_TBFILE

    iface=`sshpass -p ${TASK_RUNNER_HOST_PASSWORD} ssh -t -t -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${TASK_RUNNER_HOST_STRING} '(
       /home/stack/get_pvt_iface.py HOST4
      )'`
    sed -i "s/HOST4_IFACE/$iface/" $ABS_PATH_TBFILE

    if [ $PKG_LOCAL -eq 1 ]
    then
      sshpass -p ${TASK_RUNNER_HOST_PASSWORD} scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $ABS_PATH_TBFILE ${TASK_RUNNER_HOST_STRING}:/tmp/$TBFILE_NAME/contrail-fabric-utils/fabfile/testbeds/testbed.py
    else
      sshpass -p ${TASK_RUNNER_HOST_PASSWORD} scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $ABS_PATH_TBFILE ${TASK_RUNNER_HOST_STRING}:/tmp/$TBFILE_NAME/fabric-utils/fabfile/testbeds/testbed.py
   fi
}

function identify_tbfile {

    folder_path=${TOOLS_WS}/testbeds
    #if [ $CEPH_PROFILE == "PROF01" ];then
    #  PROFILE_TBFILE_NAME=$AVAILABLE_TESTBEDS
    #elif [ $CEPH_PROFILE == "PROF02" ];then
    #  PROFILE_TBFILE_NAME=$AVAILABLE_TESTBEDS
    #elif [ $CEPH_PROFILE == "PROF04" ];then
    #  PROFILE_TBFILE_NAME="testbed_ceph_perf_prof04.py"
    #fi
    tbfile=$folder_path/$PROFILE_TBFILE_NAME
    [ -f $tbfile ] || die "Testbed file $tbfile not found"
    export ABS_PATH_TBFILE=$tbfile

}


function copy_tbfile_task_runner {

    identify_tbfile
 
    if [ $PKG_LOCAL -eq 0 ]
    then
      sshpass -p ${TASK_RUNNER_HOST_PASSWORD} scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $ABS_PATH_TBFILE ${TASK_RUNNER_HOST_STRING}:/tmp/$TBFILE_NAME/fabric-utils/fabfile/testbeds/testbed.py
    else
      sshpass -p ${TASK_RUNNER_HOST_PASSWORD} scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $ABS_PATH_TBFILE ${TASK_RUNNER_HOST_STRING}:/tmp/$TBFILE_NAME/contrail-fabric-utils/fabfile/testbeds/testbed.py
    fi

}


function copy_tbfile_to_api_server {

  sshpass -p ${API_SERVER_HOST_PASSWORD} scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $ABS_PATH_TBFILE ${API_SERVER_HOST_STRING}:/opt/contrail/utils/fabfile/testbeds/testbed.py 

}

#####

function copy_pkgs_to_sm_node {

    if [ $COPY_BUILD_PKG_TO_TASK_RUNNER -eq 1 ]
    then
      exec_cmds -s $TASK_RUNNER_HOST_STRING -p ${TASK_RUNNER_HOST_PASSWORD}  -c "rm -rf $PKG_FILE_DIR"      
      exec_cmds -s $TASK_RUNNER_HOST_STRING -p ${TASK_RUNNER_HOST_PASSWORD}  -c "mkdir -p $PKG_FILE_DIR/artifacts_extra/"      
      exec_cmds -s $TASK_RUNNER_HOST_STRING -p ${TASK_RUNNER_HOST_PASSWORD}  -c "mkdir -p $PKG_FILE_DIR/artifacts/"      
     
      if [ $INSTALL_MODE == "SM" ]
      then
        sshpass -p ${TASK_RUNNER_HOST_PASSWORD} scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $SM_INSTALLER_PKG_FILE ${TASK_RUNNER_HOST_STRING}:$SM_INSTALLER_PKG_FILE
        sshpass -p ${TASK_RUNNER_HOST_PASSWORD} scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $INSTALL_PKG_FILE ${TASK_RUNNER_HOST_STRING}:$INSTALL_PKG_FILE
        sshpass -p ${TASK_RUNNER_HOST_PASSWORD} scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $STORAGE_PKG_FILE ${TASK_RUNNER_HOST_STRING}:$STORAGE_PKG_FILE
      fi
    fi 
}

function copy_pkg_to_api_server() {

    exec_cmds -s ${API_SERVER_HOST_STRING} -p ${API_SERVER_HOST_PASSWORD} -c "mkdir -p $PKG_FILE_DIR/artifacts_extra/"
    exec_cmds -s ${API_SERVER_HOST_STRING} -p ${API_SERVER_HOST_PASSWORD} -c "mkdir -p $PKG_FILE_DIR/artifacts/"

    exec_cmds -s ${TASK_RUNNER_HOST_STRING} -p ${TASK_RUNNER_HOST_PASSWORD} -c "
      sshpass -p ${API_SERVER_HOST_PASSWORD} scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $1 ${API_SERVER_HOST_STRING}:$1
    "

}

function create_testbed_ceph {

    search_package_ceph

    exec_cmds -s ${TASK_RUNNER_HOST_STRING} -p ${TASK_RUNNER_HOST_PASSWORD} -c "rm -rf /tmp/$TBFILE_NAME/"      
    exec_cmds -s ${TASK_RUNNER_HOST_STRING} -p ${TASK_RUNNER_HOST_PASSWORD} -c "mkdir /tmp/$TBFILE_NAME/"      

    if [ $PKG_LOCAL -eq 1 ]
    then
      exec_cmds -s ${TASK_RUNNER_HOST_STRING} -p ${TASK_RUNNER_HOST_PASSWORD} -c "
        cd /tmp/$TBFILE_NAME/;
        git clone git@github.com:Juniper/contrail-fabric-utils.git
        "
    else 
      sshpass -p ${TASK_RUNNER_HOST_PASSWORD} scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $PKG_FILE_DIR/artifacts_extra/contrail-fabric-utils*.tgz ${TASK_RUNNER_HOST_STRING}:/tmp/$TBFILE_NAME/
      exec_cmds -s ${TASK_RUNNER_HOST_STRING} -p ${TASK_RUNNER_HOST_PASSWORD} -c "cd /tmp/$TBFILE_NAME/;tar xzf contrail-fabric-utils*.tgz" 
    fi

    copy_tbfile_task_runner


}

function reimage_setup_ceph {

    if [ $SKIP_REIMAGE -eq 1 ] 
    then 
        return 0
    fi
    exec_cmds -s ${TASK_RUNNER_HOST_STRING} -p ${TASK_RUNNER_HOST_PASSWORD} -c "
            if [ $PKG_LOCAL -eq 1 ];then
              cd /tmp/$TBFILE_NAME/contrail-fabric-utils;
            else
              cd /tmp/$TBFILE_NAME/fabric-utils;
            fi
      
            export HA_TEST=$HA_TEST;
            #fab all_sm_reimage:$CLUSTER_NAME,$REIMAGE_PARAM ;
            if [ $DISTRO == "ubuntu-12-04" ]; then
              server-manager delete image --image_id ubuntu-12.04.3;
              server-manager add image -f /home/stack/image_12.04.3.json;
            else
              server-manager delete image --image_id ubuntu-14.04;
              server-manager add image -f /home/stack/image_14.04.json;
            fi 
            server-manager reimage --no_confirm --cluster_id $CLUSTER_NAME $REIMAGE_PARAM;
            fab wait_till_all_up:attempts=180,reimaged=True;
            fab check_reimage_state" || debug_and_die_local "reimage_setup failed"
}

function bringup_setup_contrail {
    if [ $SKIP_BRINGUP -ne 0 ] 
    then 
        return 0
    fi

    copy_pkg_to_api_server $INSTALL_PKG_FILE

    exec_cmds -s ${API_SERVER_HOST_STRING} -p ${API_SERVER_HOST_PASSWORD} -c "
        dpkg -i $INSTALL_PKG_FILE;
        cd /opt/contrail/contrail_packages/;
        ./setup.sh
       "
    copy_tbfile_to_api_server

    exec_cmds -s ${API_SERVER_HOST_STRING} -p ${API_SERVER_HOST_PASSWORD} -c "
          cd /opt/contrail/utils;
          fab install_pkg_all:${INSTALL_PKG_FILE} || die 'fab install_pkg_all:${INSTALL_PKG_FILE} failed'
          " || debug_and_die_local "install_pkg_all failed"

    if [[ "${DISTRO}" =~ "ubuntu" ]]; then
        exec_cmds -s ${TASK_RUNNER_HOST_STRING} -p ${TASK_RUNNER_HOST_PASSWORD} -c "
          if [ $PKG_LOCAL -eq 1 ];then
              cd /tmp/$TBFILE_NAME/contrail-fabric-utils;
          else
              cd /tmp/$TBFILE_NAME/fabric-utils;
          fi
          fab upgrade_kernel_all;
          sleep 60;
          fab wait_till_all_up:waitdown=False,attempts=30 " || debug_and_die_local "ERROR: kernel upgrade/Failed waiting for nodes to come up"
    fi

    exec_cmds -s ${API_SERVER_HOST_STRING} -p ${API_SERVER_HOST_PASSWORD} -c "
            cd /opt/contrail/utils;
            export HA_TEST=$HA_TEST;
            fab install_contrail" || debug_and_die_local "fab install_contrail failed"

    exec_cmds -s ${API_SERVER_HOST_STRING} -p ${API_SERVER_HOST_PASSWORD} -c "
            cd /opt/contrail/utils;
            export HA_TEST=$HA_TEST;
            fab setup_interface || exit 1;
            fab add_static_route 
            fab setup_all" || debug_and_die_local "fab setup_interface or setup_all task failed"
}

function bringup_storage {

    copy_pkg_to_api_server $STORAGE_PKG_FILE
        
    exec_cmds -s ${API_SERVER_HOST_STRING} -p ${API_SERVER_HOST_PASSWORD} -c "
        dpkg -i $STORAGE_PKG_FILE;
        cd /opt/contrail/contrail_packages/;
        ./setup_storage.sh
       "

    exec_cmds -s ${API_SERVER_HOST_STRING} -p ${API_SERVER_HOST_PASSWORD} -c "
            cd /opt/contrail/utils;
            fab install_storage_pkg_all:${STORAGE_PKG_FILE};
            fab install_storage;
            fab setup_storage" || debug_and_die_local "install_storage_pkg_all failed"

}

function reimage_and_bringup_ceph {

    if [ $SKIP_REIMAGE -eq 0 ]
    then
      reimage_using_SM_ceph || debug_and_die_local "Reimage failed!"
      #reimage_setup_ceph || debug_and_die_local "Reimage failed!"
    fi

    update_testbed_file || die "Unable to set the testbed properly for use"

    if [ $SKIP_CONTRAIL_BRINGUP -eq 0 ]
    then
      bringup_setup_contrail || debug_and_die_local "Bringup contrail failed!"
    fi

    if [ $SKIP_STORAGE_BRINGUP -eq 0 ]
    then
      bringup_storage || debug_and_die_local "Bringup storage failed!"
    fi
}

function run_ceph_check {

  result=`exec_cmds -s ${TASK_RUNNER_HOST_STRING} -p ${TASK_RUNNER_HOST_PASSWORD} -c  "/home/stack/check_ceph_status.py $CLUSTER_NAME $OSD_COUNT"`
  echo $result | grep "CEPH_STATUS_CHECK_OK"
  return_val=`echo $?`

  if [[ $return_val != 0 ]]
  then
    die "CEPH_STATUS_CHECK : FAILED"
  else
    echo "CEPH_STATUS_CHECK : PASS"
  fi

}

function collect_tech_support_local {
    if [ $SKIP_LOGS_COLLECTION -ne 0 ]
    then
        return 0
    fi

    dest_dir_folder=$DEBUG_LOG_DIR/CONFIG_NODE/${SCRIPT_TIMESTAMP}
    debug_cmds="export HA_TEST=$HA_TEST && fab attach_logs_cores:$DEBUG_LOG_DIR/CONFIG_NODE,${SCRIPT_TIMESTAMP} ; cp fabfile/testbeds/testbed.py $dest_dir_folder ;  cp *.log $dest_dir_folder"
          
    exec_cmds -s ${API_SERVER_HOST_STRING} -p ${API_SERVER_HOST_PASSWORD} -c "
            cd /opt/contrail/utils;
            $debug_cmds"
}


function debug_and_die_local
{
    local message=$1
    if [ $LOCK_TESTBED_ON_FAILURE = 1 ]; then
        echo "Testbed is set to be locked on failure"
        if [[ $message =~ 'Test failures exceed' ]]; then
            collect_tech_support_local
        fi
        export RELEASE_TESTBED=0
        (  
            set -x
            flock 5
            echo "Locking testbed $tb_lock_file for debugging"
            echo "Testbed locked..Unlock when debug complete" >> $tb_lock_file
            cat $tb_lock_file
        ) 5>${LOCK_FILE_DIR}/lockfile
    else
        collect_tech_support_local
    fi
    [ -z "$message" ] && message="Died"
    echo "${BASH_SOURCE[1]}: line ${BASH_LINENO[0]}: ${FUNCNAME[1]}: $message." >&2
    cat $tb_lock_file
    exit 1
}
function run_ceph_fab_sanity() {
    echo "Running tests on $TBFILE_NAME .." 
    create_testbed_ceph
    reimage_and_bringup_ceph
    copy_tbfile_to_api_server
    #run_ceph_check || die "run_ceph_check step failed"
    echo "Test Done" 
    collect_tech_support_local || die "Task to collect logs/cores failed"
    echo "Ending test on $TBFILE_NAME"
}
